app = "bot-citas-jcrosas-pasto"  # Ej: "bot-citas-jcrosas"
primary_region = "iad"          # Región recomendada (Virginia, EE.UU.)

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 3000          # Puerto donde corre tu app
  force_https = true            # Obliga HTTPS
  auto_stop_machines = false    # Evita que se duerma
  auto_start_machines = true    # Siempre activo
  min_machines_running = 1      # Mantiene al menos 1 instancia

[env]
  NODE_ENV = "production"
